### ISSUE TITLE
你好,我也在做GB28181信令服务器

### ISSUE THREAD

**Issue by lutongzero** [swwheihei/wvp#1]
我也在做GB28181信令服务器,咱们可以一起交流,探讨[gb8181](https://github.com/lutongzero/gb28181)

**Comment by swwheihei** [comment]
可以的，代码刚上传

**Comment by urmyfaith** [comment]
我也在做GB28181 设备的接入，能加个好友，一起学习么？ 

@lutongzero @swwheihei 

Q◎Q  ⑨○④③①②○❼❷
