### ISSUE TITLE
注册设备时，密码错误

### ISSUE THREAD

**Issue by MenWhyHan** [swwheihei/wvp#3]
使用海康的NVR设备，请求的参数与协议中不同的地方就是Authentication中Authentication URI为"sip:34020000002000000001@3402000000"，请问可能是什么情况

**Comment by swwheihei** [comment]
1、检查设备配置的密码是否正确
2、确认设备是否支持2016版标准，2011版标准的认证暂时还不支持

**Comment by MenWhyHan** [comment]
感谢，应该是设备设置的错误，后面换了几个密码测试都注册成功了
