### ISSUE TITLE
大佬,打扰一下,我刚才看了一下playbackStreamCmd(SIPCommander.java)方法中request(212行)那个第四个参数,是还要填写live嘛?

### ISSUE THREAD

**Issue by angelshowzhe** [swwheihei/wvp#4]
大佬,打扰一下,我刚才看了一下playbackStreamCmd(SIPCommander.java)方法中request(212行)那个第四个参数,是还要填写live吗? 学习阶段,如若有误还请海涵

**Comment by swwheihei** [comment]
回放还没有完成，那一块代码还没有走通呢，不具有参考意义。等Readme中更新视频回放为已完成的时候你再参考吧

**Comment by angelshowzhe** [comment]
> 回放还没有完成，那一块代码还没有走通呢，不具有参考意义。等Readme中更新视频回放为已完成的时候你再参考吧
好的,辛苦了
